version: "3.8"
services:
  server:
    env_file:
    - .docker.env
    build:
      context: .
      target: final 
    ports:
      - 8000:8000
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - db 
      - redis 
  db:
    image: postgres:15
    container_name: usd-rate-postgres 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: rates 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:5
    container_name: usd-rate-redis 
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
